version: '3.8'

services:
  globetrotter:
    build: .
    container_name: globetrotter-app
    ports:
      - "5000:5000"
    volumes:
      # Monte le dossier data pour persister les données
      - ./data:/app/data
    environment:
      - SECRET_KEY=globetrotter-secret-change-in-prod
      - FLASK_DEBUG=0
    restart: unless-stopped
    networks:
      - globetrotter-network

networks:
  globetrotter-network:
    driver: bridge